#spring:
#  datasource:
#    username: root
#    password: Welcome@1
#    url: dbc:mysql://localhost:3306/springcrud
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect: oorg.hibernate.dialect.MySQL5Dialect
